"""Audit 0.6.9 regressions for codebeacon/contextmap/generator.py.

G09 — CLAUDE.md section wipe (data-loss, high):
    _strip_codebeacon_block flipped into delete-mode on any generic heading in
    _LEGACY_PATTERNS ("## Architecture", "## Common Commands", …). Those are
    exactly what Claude Code's /init writes, so a hand-authored CLAUDE.md had
    its user sections silently deleted on the FIRST (marker-less) scan. The fix
    gates the legacy heuristic behind a positive codebeacon fingerprint and
    anchors the strip to the Lookup-strategy header + footer.

G11 — inconsistent Services counts (medium):
    The Projects table and Step-2 Notes column folded controller classes into
    "Services" (services + controllers) while the Architecture section and the
    wiki reported services only, so one document disagreed with itself. The fix
    unifies every surface on services-only.

Round-2 fixups (0.6.9 adversarial review):
    G11 — contextmap _CONTROLLER_ANNS only held the '@'-prefixed / bracketed
    forms, but the Spring/NestJS extractors emit annotations WITHOUT the '@'
    (e.g. ['RestController']). So an annotation-only @RestController class that
    is NOT named *Controller was counted as a service by CLAUDE.md while the
    wiki (whose _CONTROLLER_ANNOTATIONS includes the bare forms) counted it as a
    controller — the two committed artifacts disagreed. contextmap now reuses
    wiki/generator._CONTROLLER_ANNOTATIONS so the counts always match.

    G09 — the marker-less legacy strip is now FOOTER-ANCHORED: it fires only
    when a "_Generated by [codebeacon]" footer exists, removing from the
    block-start heading (a Lookup header, else the first legacy heading) through
    the footer inclusive. A no-footer file is returned 100% unchanged; a
    fingerprinted file with a footer but no Lookup header is stripped (no more
    duplication on merge).

    _pick_example_note now picks deterministically (min by (label, node_id)) so
    the CLAUDE.md Example column no longer flips with graph insertion order.
"""
from __future__ import annotations

import re
from pathlib import Path

import networkx as nx

from codebeacon.common.types import ProjectInfo
from codebeacon.contextmap.generator import (
    _collect_stats,
    _merge_content,
    _pick_example_note,
    _strip_codebeacon_block,
    generate_context_map,
)
from codebeacon.wiki.generator import _is_controller


# ── G09: section-wipe / data-loss ────────────────────────────────────────────

# A realistic hand-written CLAUDE.md (e.g. from Claude Code /init): generic
# headings that also appear in codebeacon output, but zero codebeacon signature.
_HANDWRITTEN = """\
# CLAUDE.md

Hand-written guidance. Checked into git by a human.

## Architecture

CRITICAL: the `auth` service is the ONLY component allowed to mint tokens.
This is a modular monolith; the billing package owns money.

## Common Commands

make deploy-prod   # requires 2 approvals — DO NOT run casually

## Gotchas

The staging DB is shared; truncating it breaks three other teams.
"""


class TestStripLeavesUserContentAlone:
    def test_handwritten_file_returned_unchanged(self):
        # No codebeacon fingerprint → 100% user content, nothing stripped.
        out = _strip_codebeacon_block(_HANDWRITTEN)
        for needle in (
            "ONLY component allowed to mint tokens",
            "modular monolith",
            "billing package owns money",
            "make deploy-prod",
            "requires 2 approvals",
            "## Architecture",
            "## Common Commands",
            "truncating it breaks three other teams",
        ):
            assert needle in out, f"lost user content: {needle!r}"

    def test_merge_preserves_all_user_sections(self, tmp_path):
        # _merge_content prepends the new block but must keep every user line.
        p = tmp_path / "CLAUDE.md"
        p.write_text(_HANDWRITTEN, encoding="utf-8")
        merged = _merge_content("# codebeacon block\n\n_Generated by [codebeacon](x)_", p)
        for needle in (
            "ONLY component allowed to mint tokens",
            "make deploy-prod",
            "requires 2 approvals",
            "## Architecture",
            "## Common Commands",
            "truncating it breaks three other teams",
        ):
            assert needle in merged, f"_merge_content dropped user content: {needle!r}"

    def test_pure_user_file_with_only_generated_footer_substring(self):
        # A user who *mentions* codebeacon in prose but has no block still keeps
        # their headings intact (footer signature present, but no start header →
        # nothing gets entered, so nothing is stripped).
        txt = _HANDWRITTEN + "\nWe run `codebeacon` weekly; see .codebeacon/wiki/ for the index.\n"
        out = _strip_codebeacon_block(txt)
        assert "ONLY component allowed to mint tokens" in out
        assert "make deploy-prod" in out


class TestStripHandlesRealCodebeaconContent:
    # A legacy (marker-less) codebeacon file: user "## Architecture" both ABOVE
    # and (via ## Gotchas) BELOW the generated block must survive; the block
    # itself — including ITS OWN "## Architecture" — must be removed.
    _LEGACY = """\
# CLAUDE.md

## Architecture

USER: auth is the ONLY service allowed to mint tokens.

## Lookup Strategy

### Step 1 → codebeacon wiki
.codebeacon/wiki/index.md

## Projects

| demo | fastapi | 0 | 1 | 0 | 0 |

## Architecture

**demo**: fastapi
  Routes: 0 | Services: 1 | Entities: 0 | Components: 0

_Generated by [codebeacon](https://x) · 2026-01-01_

## Gotchas

USER: staging DB is shared; do not truncate.
"""

    def test_user_sections_survive_block_is_stripped(self):
        out = _strip_codebeacon_block(self._LEGACY)
        # user content survives (above and below the block)
        assert "ONLY service allowed to mint tokens" in out
        assert "staging DB is shared" in out
        # codebeacon block removed
        assert ".codebeacon/wiki" not in out
        assert "_Generated by" not in out
        assert "| demo | fastapi | 0 | 1" not in out

    def test_marker_delimited_block_still_stripped(self):
        # Format 1 (markers) must keep working: block removed, user text kept.
        txt = (
            "<!-- codebeacon:start -->\n"
            "## Lookup strategy\n_Generated by [codebeacon](x)_\n"
            "<!-- codebeacon:end -->\n\n"
            "## Architecture\n\nUSER note that must survive.\n"
        )
        out = _strip_codebeacon_block(txt)
        assert "USER note that must survive." in out
        assert "## Architecture" in out
        assert "codebeacon:start" not in out
        assert "_Generated by" not in out


def test_generate_context_map_preserves_handwritten_claude_md(tmp_path):
    # End-to-end via the public API against a hand-written CLAUDE.md.
    (tmp_path / ".codebeacon").mkdir()
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(_HANDWRITTEN, encoding="utf-8")

    G = nx.DiGraph()
    G.add_node("n1", project="demo", type="class", label="AuthService",
               source_file=str(tmp_path / "auth.py"))
    projects = [ProjectInfo(name="demo", path=str(tmp_path), framework="fastapi",
                            language="python", signature_file="pyproject.toml")]

    generate_context_map(G, tmp_path / ".codebeacon", projects, targets=["CLAUDE.md"])

    after = claude.read_text(encoding="utf-8")
    for needle in (
        "ONLY component allowed to mint tokens",
        "make deploy-prod",
        "requires 2 approvals",
        "truncating it breaks three other teams",
    ):
        assert needle in after, f"generate_context_map wiped user content: {needle!r}"
    # And it actually prepended the generated block.
    assert "<!-- codebeacon:start -->" in after


# ── G11: internally-consistent Services counts ───────────────────────────────

def _backend_graph_with_controllers() -> nx.DiGraph:
    """2 controller classes + 3 plain service classes + 1 entity, one project."""
    G = nx.DiGraph()
    G.add_node("b1", project="backend", type="class", label="UserController",
               annotations=["@RestController"], source_file="/repo/backend/UserController.java")
    G.add_node("b2", project="backend", type="class", label="OrderController",
               annotations=["@RestController"], source_file="/repo/backend/OrderController.java")
    G.add_node("b3", project="backend", type="class", label="UserService",
               annotations=["@Service"], source_file="/repo/backend/UserService.java")
    G.add_node("b4", project="backend", type="class", label="OrderService",
               annotations=["@Service"], source_file="/repo/backend/OrderService.java")
    G.add_node("b5", project="backend", type="class", label="PaymentGateway",
               annotations=[], source_file="/repo/backend/PaymentGateway.java")
    G.add_node("b6", project="backend", type="entity", label="User",
               source_file="/repo/backend/User.java")
    return G


def _render_claude_md(G, projects, tmp_path) -> str:
    cb = tmp_path / ".codebeacon"
    cb.mkdir()
    written = generate_context_map(G, cb, projects, targets=["CLAUDE.md"])
    return Path(written[0]).read_text(encoding="utf-8")


def test_projects_table_services_matches_architecture(tmp_path):
    G = _backend_graph_with_controllers()
    projects = [ProjectInfo(name="backend", path="/repo/backend",
                            framework="spring-boot", language="java",
                            signature_file="pom.xml")]
    text = _render_claude_md(G, projects, tmp_path)

    proj_row = re.search(r"\| backend \| spring-boot \| \d+ \| (\d+) \|", text)
    arch = re.search(r"\*\*backend\*\*:.*?\n\s*Routes: \d+ \| Services: (\d+) \|",
                     text, re.S)
    notes = re.search(r"\| backend \| (\d+) services", text)

    assert proj_row is not None and arch is not None and notes is not None
    # All three surfaces agree, and on services-ONLY (3, not 3+2 controllers).
    assert proj_row.group(1) == arch.group(1) == notes.group(1) == "3", (
        f"Projects={proj_row.group(1)} Notes={notes.group(1)} "
        f"Architecture={arch.group(1)} — expected all == 3 (services only)"
    )


def test_project_with_only_controllers_reports_zero_services(tmp_path):
    # A project of pure controllers → Services == 0 everywhere (was == 2 in the
    # Projects table before the fix).
    G = nx.DiGraph()
    G.add_node("c1", project="edge", type="class", label="PingController",
               annotations=["@RestController"], source_file="/repo/edge/PingController.java")
    G.add_node("c2", project="edge", type="class", label="HealthController",
               annotations=["@RestController"], source_file="/repo/edge/HealthController.java")
    projects = [ProjectInfo(name="edge", path="/repo/edge",
                            framework="spring-boot", language="java",
                            signature_file="pom.xml")]
    text = _render_claude_md(G, projects, tmp_path)

    proj_row = re.search(r"\| edge \| spring-boot \| \d+ \| (\d+) \|", text)
    arch = re.search(r"\*\*edge\*\*:.*?\n\s*Routes: \d+ \| Services: (\d+) \|",
                     text, re.S)
    assert proj_row.group(1) == arch.group(1) == "0"


# ── G11 round-2: contextmap ↔ wiki controller-count parity ───────────────────

def test_bare_restcontroller_annotation_agrees_with_wiki():
    """A @RestController class NOT named *Controller must be classified the same
    way by contextmap (_collect_stats) and the wiki (_is_controller).

    The extractor emits the annotation WITHOUT the leading '@' (['RestController']),
    which the '@'-only _CONTROLLER_ANNS missed — contextmap called it a service
    while the wiki called it a controller, so CLAUDE.md and the wiki disagreed.
    """
    G = nx.DiGraph()
    # Mirrors extract_services output: annotation is the bare identifier.
    G.add_node("n1", project="svc", type="class", label="HealthEndpoint",
               annotations=["RestController"], source_file="/r/HealthEndpoint.java")
    G.add_node("n2", project="svc", type="class", label="BillingService",
               annotations=["Service"], source_file="/r/BillingService.java")

    ctx_services = _collect_stats(G)["svc"]["services"]
    wiki_services = sum(
        1 for _n, d in G.nodes(data=True)
        if d.get("type") == "class"
        and not _is_controller(d.get("label", ""), d.get("annotations", []))
    )
    # Both surfaces must count exactly one service (BillingService); the bare
    # @RestController HealthEndpoint is a controller on both.
    assert ctx_services == wiki_services == 1
    # And contextmap must NOT count the bare-annotation controller as a service.
    assert _collect_stats(G)["svc"]["controllers"] == 1


def test_restcontroller_parity_end_to_end_as_extracted(tmp_path):
    """End-to-end 'as extracted' pin: run the real Spring extractor, then assert
    the CLAUDE.md Services count equals the wiki service_count."""
    from codebeacon.extract.services import extract_services

    java = tmp_path / "HealthEndpoint.java"
    java.write_text(
        "package demo;\n"
        "@RestController\npublic class HealthEndpoint { public String ping(){return \"ok\";} }\n"
        "@Service\npublic class BillingService { public void charge(){} }\n",
        encoding="utf-8",
    )
    svcs, _ = extract_services(str(java), "spring-boot")
    G = nx.DiGraph()
    for s in svcs:
        G.add_node(s.class_name, project="backend", type="class", label=s.class_name,
                   annotations=list(s.annotations), source_file=s.source_file)

    projects = [ProjectInfo(name="backend", path=str(tmp_path), framework="spring-boot",
                            language="java", signature_file="pom.xml")]
    text = _render_claude_md(G, projects, tmp_path)

    proj_row = re.search(r"\| backend \| spring-boot \| \d+ \| (\d+) \|", text)
    wiki_service_count = sum(
        1 for _n, d in G.nodes(data=True)
        if d.get("type") == "class"
        and not _is_controller(d.get("label", ""), d.get("annotations", []))
    )
    assert proj_row is not None
    assert int(proj_row.group(1)) == wiki_service_count == 1


# ── G09 round-2: footer-anchored legacy strip ────────────────────────────────

class TestFooterAnchoredStrip:
    # (a) Hand-written file with a `.codebeacon/wiki/` mention AND its own
    # `## Lookup strategy`, but NO footer → returned 100% unchanged.
    _NO_FOOTER_WITH_WIKI = """\
# CLAUDE.md

## Lookup strategy

> Check `.codebeacon/wiki/` first, then our internal runbook.
> CRITICAL: production DB credentials live in Vault — NEVER commit them to git.
> On-call rotation: page #sre before touching the payment path.

## Deployment

make deploy-prod requires two approvals.
"""

    def test_no_footer_file_returned_unchanged(self):
        out = _strip_codebeacon_block(self._NO_FOOTER_WITH_WIKI)
        # Byte-for-byte unchanged (modulo the leading/trailing whitespace strip).
        assert out == self._NO_FOOTER_WITH_WIKI.strip()
        for needle in (
            "CRITICAL: production DB credentials",
            "page #sre before touching",
            "## Lookup strategy",
            ".codebeacon/wiki/",
            "make deploy-prod",
        ):
            assert needle in out, f"lost user content: {needle!r}"

    # (b) Fingerprinted file WITH a footer but NO Lookup header → the old block
    # is stripped from the first legacy heading through the footer, so a re-merge
    # does not duplicate the codebeacon content.
    _FOOTER_NO_LOOKUP = """\
# CLAUDE.md

## Projects

| demo | fastapi | 0 | 1 | 0 | 0 |

See .codebeacon/wiki/ for details.

## Architecture

**demo**: fastapi

_Generated by [codebeacon](https://x) · 2026-01-01_
"""

    def test_footer_without_lookup_heading_is_stripped(self):
        out = _strip_codebeacon_block(self._FOOTER_NO_LOOKUP)
        # Everything from the first legacy heading (## Projects) through the
        # footer is removed; only the user's `# CLAUDE.md` title survives.
        assert out == "# CLAUDE.md"
        assert "## Projects" not in out
        assert "_Generated by" not in out
        assert "| demo | fastapi | 0 | 1" not in out

    def test_merge_twice_has_no_duplication_for_footer_without_lookup(self, tmp_path):
        p = tmp_path / "CLAUDE.md"
        p.write_text(self._FOOTER_NO_LOOKUP, encoding="utf-8")
        new_block = (
            "# CLAUDE.md\n\n## Projects\n\n| demo | fastapi | 0 | 1 | 0 | 0 |\n\n"
            "_Generated by [codebeacon](y) · 2026-07-11_"
        )
        first = _merge_content(new_block, p)
        p.write_text(first, encoding="utf-8")
        second = _merge_content(new_block, p)

        # Single footer + single Projects table after re-merge (no duplication).
        assert first.count("_Generated by [codebeacon]") == 1
        assert second.count("_Generated by [codebeacon]") == 1
        assert second.count("## Projects") == 1

    # (c) Marker-delimited files still take the Format-1 path (footer inside the
    # block does not leak), and user content below the markers survives.
    def test_marker_file_with_footer_inside_block_unchanged_semantics(self):
        txt = (
            "<!-- codebeacon:start -->\n"
            "## Lookup strategy\n\n## Projects\n\n"
            "_Generated by [codebeacon](x) · 2026-01-01_\n"
            "<!-- codebeacon:end -->\n\n"
            "## My Notes\n\nkeep me.\n"
        )
        out = _strip_codebeacon_block(txt)
        assert "keep me." in out
        assert "## My Notes" in out
        assert "## Projects" not in out
        assert "_Generated by" not in out
        assert "codebeacon:start" not in out


# ── Determinism: _pick_example_note picks a stable key, not insertion order ───

def test_pick_example_note_is_insertion_order_independent():
    def build(order):
        G = nx.DiGraph()
        for nid, label, sf in order:
            G.add_node(nid, project="p", type="class", label=label, source_file=sf)
        return G

    fwd = build([("n1", "Zebra", "/r/Zebra.py"), ("n2", "Apple", "/r/Apple.py")])
    rev = build([("n2", "Apple", "/r/Apple.py"), ("n1", "Zebra", "/r/Zebra.py")])
    # min by (label, node_id): "Apple" wins regardless of insertion order.
    assert _pick_example_note(fwd, "p") == _pick_example_note(rev, "p") == "Apple.py.md"


def test_example_column_stable_across_node_order(tmp_path):
    def build(order):
        G = nx.DiGraph()
        for nid, label, sf in order:
            G.add_node(nid, project="p", type="class", label=label, source_file=sf)
        return G

    projects = [ProjectInfo(name="p", path="/r", framework="fastapi",
                            language="python", signature_file="pyproject.toml")]

    def example_cell(G, sub):
        cb = tmp_path / sub / ".codebeacon"
        cb.mkdir(parents=True)
        written = generate_context_map(G, cb, projects, targets=["CLAUDE.md"])
        text = Path(written[0]).read_text(encoding="utf-8")
        return re.search(r"\| p \|[^|]*\| `([^`]+)` \|", text).group(1)

    fwd = build([("n1", "Zebra", "/r/Zebra.py"), ("n2", "Apple", "/r/Apple.py")])
    rev = build([("n2", "Apple", "/r/Apple.py"), ("n1", "Zebra", "/r/Zebra.py")])
    assert example_cell(fwd, "a") == example_cell(rev, "b") == "Apple.py.md"
